# Generated by Django 2.1.4 on 2018-12-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tipo', models.CharField(choices=[('Producto 1', 'Producto 1'), ('Producto 2', 'Producto 2'), ('Producto 3', 'Producto 3')], default='Producto 1', max_length=10)),
            ],
        ),
    ]
