# Generated by Django 2.1.4 on 2018-12-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_v', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombre_p',
        ),
        migrations.RenameField(
            model_name='tienda',
            old_name='nombre',
            new_name='nombre_t',
        ),
        migrations.AddField(
            model_name='tienda',
            name='encarg_tienda',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
