# Generated by Django 2.1.4 on 2018-12-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20181206_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_p',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='tienda',
            old_name='nombre_t',
            new_name='nombre_tienda',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='nombre_v',
            new_name='nombre_vendedor',
        ),
    ]
