# Generated by Django 2.1.4 on 2018-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20181206_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imageUrl',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Notebooks', 'Notebooks'), ('Tarjeta_Grafica', 'Tarjeta_Grafica'), ('Audifonos', 'Audifonos'), ('Computadores', 'Computadores')], default='Notebooks', max_length=10),
        ),
    ]
