# Generated by Django 2.1.4 on 2018-12-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20181213_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='email_v',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='password_v',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Notebooks', 'Notebooks'), ('Tarjeta_Grafica', 'Tarjeta_Grafica'), ('Audifonos', 'Audifonos'), ('Computadores', 'Computadores')], default='Notebooks', max_length=20),
        ),
    ]
